# Generated by Django 5.0.6 on 2024-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='image',
            name='additional_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
