# Generated by Django 5.0.6 on 2024-07-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_management', '0003_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('is_in_use', models.BooleanField(default=False)),
                ('type', models.TextField()),
                ('additional_id', models.BigIntegerField(blank=True, null=True)),
                ('url', models.TextField()),
                ('file_path', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
    ]
