# Generated by Django 5.0.6 on 2024-07-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file_path',
            new_name='path',
        ),
    ]
