# Generated by Django 5.0.6 on 2024-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0005_rename_file_path_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
