# Generated by Django 5.0.7 on 2024-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0006_alter_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('active', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
