# Generated by Django 5.0.7 on 2024-08-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField()),
                ('path', models.TextField()),
                ('active', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
