# Generated by Django 5.0.7 on 2024-08-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0010_alter_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('user_id', models.BigIntegerField()),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_management.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_management.store'),
        ),
    ]
