# Generated by Django 5.0.7 on 2024-08-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0011_store_image_store_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='path',
        ),
        migrations.RemoveField(
            model_name='store',
            name='path',
        ),
    ]
