# Generated by Django 5.0.7 on 2024-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0013_store_image_path_store_image_url_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
