# Generated by Django 5.0.7 on 2024-08-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0014_productimage_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_in_use',
        ),
        migrations.CreateModel(
            name='CetegoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_use', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('image_size', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_management.category')),
            ],
        ),
    ]
