# Generated by Django 5.0.7 on 2024-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0015_remove_category_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
