# Generated by Django 5.0.7 on 2024-08-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0016_category_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cetegoryimage',
            old_name='image_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='cetegoryimage',
            old_name='image_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='cetegoryimage',
            old_name='image_url',
            new_name='url',
        ),
    ]
