# Generated by Django 5.0.7 on 2024-08-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0017_rename_image_path_cetegoryimage_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cetegoryimage',
            name='is_in_use',
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_management.store')),
            ],
        ),
    ]
