# Generated by Django 5.0.7 on 2024-08-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0018_remove_cetegoryimage_is_in_use_storeimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreImage',
            new_name='StoreLogo',
        ),
    ]
