# Generated by Django 5.0.7 on 2024-08-24 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0019_rename_storeimage_storelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cetegoryimage',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_management.store'),
        ),
    ]
