# Generated by Django 5.0.7 on 2024-08-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0020_cetegoryimage_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cetegoryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
