# Generated by Django 5.0.7 on 2024-08-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0021_cetegoryimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='text_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
