# Generated by Django 5.0.7 on 2024-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0022_store_text_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelogo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
