# Generated by Django 5.0.7 on 2024-08-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0023_storelogo_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelogo',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='files_management.store'),
        ),
    ]
