# Generated by Django 5.0.7 on 2024-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0024_alter_storelogo_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
