# Generated by Django 5.0.7 on 2024-08-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0025_alter_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='text_id',
            new_name='domain',
        ),
    ]
