# Generated by Django 5.0.7 on 2024-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0028_storefavicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_in_use', models.BooleanField(default=False)),
                ('type', models.TextField()),
                ('url', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
