# Generated by Django 5.0.7 on 2024-09-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0029_storeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeimage',
            name='user_id',
        ),
        migrations.AddField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_management.store'),
        ),
    ]
