# Generated by Django 5.0.7 on 2024-09-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0030_remove_storeimage_user_id_storeimage_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cetegoryimage',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='files_management.category'),
        ),
    ]
